# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    projects: 'Sources/Microcharts/Microcharts.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: 'Sources/Microcharts/Microcharts.csproj'

- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: 'Sources/Microcharts/Microcharts.csproj'
    includesymbols: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: push to feed
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e78193ab-d5a9-437a-b947-6a7096fe9790'